services:
  # Backend API Service (Using External MongoDB & Redis)
  - type: web
    name: instabot-backend
    env: node
    plan: free
    buildCommand: cd backend && npm install --production
    startCommand: cd backend && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: MONGODB_URI
        value: mongodb+srv://instabot-user:instabot123@cluster0.vuv.mongodb.net/instabot-private?retryWrites=true&w=majority
      - key: REDIS_URL
        value: redis://default:bjDz54jWIyNvHDF8uRm8CyW5CiDFVa01@redis-11735.c245.us-east-1-3.ec2.redns.redis-cloud.com:11735
      - key: JWT_SECRET
        value: your-super-secret-jwt-key-for-private-app
      - key: META_APP_ID
        value: 1419703882459970
      - key: META_APP_SECRET
        value: 75cfd3595ac08e9397565d93eaf0b193
      - key: META_WEBHOOK_VERIFY_TOKEN
        value: fraudprotect-webhook-token-2024
      - key: FACEBOOK_ACCESS_TOKEN
        value: EAAULNpGZAq0IBPcZBtBlu4ZAFd2I0ySP7xEmr24m3PxczSAzAwRsLEJWAxqI0Da8AJAhZA8E0dVLw0eoenwqPIv0elgU6JCuqcvZCZABfZCg3qgn07xj3rtJtzXnZCofnps339TPmHYtwjOwKo4QQnPvOdL3nOpgRj8KavgL8x7W5kIvtHfza6uoZAoOZBVO8QeEzv3FPaAQkAcUWs3SDcht9Xu2cewYQZBivGNsRwL0apZA
      - key: FACEBOOK_PAGE_ID
        value: 1935878793391260
      - key: INSTAGRAM_APP_ID
        value: 628630250112579
      - key: INSTAGRAM_APP_SECRET
        value: 77387e4f58158b619bbee9d6906979bb
      - key: ENCRYPTION_KEY
        value: be77388d322e34a1e7ae6cc39d360cbec52cdb850b560d3dc147b031a21c4e1d
      - key: DISABLE_SUBSCRIPTION_BILLING
        value: true
      - key: DISABLE_USER_AUTHENTICATION
        value: true
      - key: PRIVATE_APP_MODE
        value: true
      - key: TEST_MODE
        value: true
      - key: TEST_POST_ID
        value: 1705521123601620
      - key: FRONTEND_URL
        value: https://instabot-frontend.onrender.com
      - key: BACKEND_URL
        value: https://instabot-backend.onrender.com
      - key: ENABLE_REGISTRATION
        value: false
      - key: ENABLE_EMAIL_VERIFICATION
        value: false
      - key: ENABLE_TWO_FACTOR_AUTH
        value: false
      - key: BOT_ENABLED
        value: true
      - key: BOT_DELETE_ENABLED
        value: false
      - key: LOG_LEVEL
        value: info
      - key: HEALTH_CHECK_ENABLED
        value: true
    healthCheckPath: /health
    autoDeploy: true

  # Frontend Web Service (Lightweight)
  - type: web
    name: instabot-frontend
    env: static
    plan: free
    buildCommand: cd frontend && npm install && npm run build
    staticPublishPath: ./frontend/dist
    envVars:
      - key: VITE_API_URL
        value: https://instabot-backend.onrender.com
    autoDeploy: true
